@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray
title Chart Map for alfresco-dbp:0.4.0
'There are 11 referenced Helm Charts
artifact "alfresco-process-services:0.1.0\n====\n\talfresco-process-services\n====\n\t0.1.0\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: " as alfresco_process_services_0_1_0 #Gainsboro
artifact "postgresql:0.9.3\n====\n\tpostgresql\n====\n\t0.9.3\n====\n\tMaintainers: databus23\n====\n\tKeywords: postgresql, postgres, database, sql" as postgresql_0_9_3 #LightSlateGray
artifact "alfresco-api-gateway:0.1.0\n====\n\talfresco-api-gateway\n====\n\t0.1.0\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: " as alfresco_api_gateway_0_1_0 #BlanchedAlmond
artifact "alfresco-activiti-cloud-registry:0.1.0\n====\n\talfresco-activiti-cloud-registry\n====\n\t0.1.0\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: " as alfresco_activiti_cloud_registry_0_1_0 #LightSlateGrey
artifact "alfresco-infrastructure:0.1.0\n====\n\talfresco-infrastructure\n====\n\t0.1.0\n====\n\tMaintainers: \n====\n\tKeywords: " as alfresco_infrastructure_0_1_0 #Cornsilk
artifact "alfresco-keycloak:0.1.0\n====\n\talfresco-keycloak\n====\n\t0.1.0\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: " as alfresco_keycloak_0_1_0 #Cyan
artifact "alfresco-sync-service:0.1.0\n====\n\talfresco-sync-service\n====\n\t0.1.0\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: syncservice, alfresco, application" as alfresco_sync_service_0_1_0 #CadetBlue
artifact "alfresco-content-services:0.0.1\n====\n\talfresco-content-services\n====\n\t0.0.1\n====\n\tMaintainers: \n====\n\tKeywords: content, content services, alfresco, alfresco content services" as alfresco_content_services_0_0_1 #Gainsboro
artifact "activemq:0.1.0\n====\n\tactivemq\n====\n\t0.1.0\n====\n\tMaintainers: \n====\n\tKeywords: " as activemq_0_1_0 #LightCoral
artifact "rabbitmq-ha:0.1.1\n====\n\trabbitmq-ha\n====\n\t0.1.1\n====\n\tMaintainers: etiennetremel\n====\n\tKeywords: rabbitmq, message queue, AMQP" as rabbitmq_ha_0_1_1 #Chocolate
artifact "alfresco-dbp:0.4.0\n====\n\talfresco-dbp\n====\n\t0.4.0\n====\n\tMaintainers: Alfresco Platform Services Team\n====\n\tKeywords: alfresco, dbp, platform" as alfresco_dbp_0_4_0 #LightSkyBlue
'There are 10 referenced Images
usecase "Image\n====\n\tDocker Hub\n====\n\talfresco/alfresco-pdf-renderer\n====\n\tlatest" as alfresco_alfresco_pdf_renderer_latest #Cornsilk
usecase "Image\n====\n\tDocker Hub\n====\n\talfresco/alfresco-share\n====\n\t6.0.a" as alfresco_alfresco_share_6_0_a #LightSeaGreen
usecase "Image\n====\n\tDocker Hub\n====\n\talfresco/alfresco-keycloak\n====\n\tlatest" as alfresco_alfresco_keycloak_latest #Khaki
usecase "Image\n====\n\tDocker Hub\n====\n\tpostgres\n====\n\t10.1" as postgres_10_1 #Ivory
usecase "Image\n====\n\tDocker Hub\n====\n\tpostgres\n====\n\t9.4.6" as postgres_9_4_6 #Ivory
usecase "Image\n====\n\tDocker Hub\n====\n\tactiviti/activiti-cloud-registry\n====\n\tlatest" as activiti_activiti_cloud_registry_latest #CadetBlue
usecase "Image\n====\n\tDocker Hub\n====\n\twebcenter/activemq\n====\n\tlatest" as webcenter_activemq_latest #GhostWhite
usecase "Image\n====\n\tDocker Hub\n====\n\talfresco/alfresco-libreoffice\n====\n\tlatest" as alfresco_alfresco_libreoffice_latest #LightSlateGray
usecase "Image\n====\n\tDocker Hub\n====\n\talfresco/process-services\n====\n\t1.8.0" as alfresco_process_services_1_8_0 #LightBlue
usecase "Image\n====\n\tquay.io\n====\n\talfresco/service-sync:2.2-SNAPSHOT\n====\n\t2.2-SNAPSHOT" as quay_io_alfresco_service_sync_2_2_SNAPSHOT #LightSalmon
alfresco_dbp_0_4_0--[#green]-|>alfresco_sync_service_0_1_0
alfresco_sync_service_0_1_0--[#green]-|>postgresql_0_9_3
alfresco_dbp_0_4_0--[#green]-|>alfresco_infrastructure_0_1_0
alfresco_infrastructure_0_1_0--[#green]-|>alfresco_keycloak_0_1_0
alfresco_infrastructure_0_1_0--[#green]-|>activemq_0_1_0
alfresco_infrastructure_0_1_0--[#green]-|>alfresco_activiti_cloud_registry_0_1_0
alfresco_infrastructure_0_1_0--[#green]-|>alfresco_api_gateway_0_1_0
alfresco_infrastructure_0_1_0--[#green]-|>rabbitmq_ha_0_1_1
alfresco_dbp_0_4_0--[#green]-|>alfresco_content_services_0_0_1
alfresco_content_services_0_0_1--[#green]-|>postgresql_0_9_3
alfresco_content_services_0_0_1--[#green]-|>alfresco_infrastructure_0_1_0
alfresco_dbp_0_4_0--[#green]-|>alfresco_process_services_0_1_0
alfresco_process_services_0_1_0--[#green]-|>postgresql_0_9_3
alfresco_process_services_0_1_0--[#green]-|>alfresco_infrastructure_0_1_0
alfresco_process_services_0_1_0--[#orange]-|>alfresco_process_services_1_8_0
postgresql_0_9_3--[#orange]-|>postgres_10_1
postgresql_0_9_3--[#orange]-|>postgres_9_4_6
alfresco_activiti_cloud_registry_0_1_0--[#orange]-|>activiti_activiti_cloud_registry_latest
alfresco_keycloak_0_1_0--[#orange]-|>alfresco_alfresco_keycloak_latest
alfresco_sync_service_0_1_0--[#orange]-|>quay_io_alfresco_service_sync_2_2_SNAPSHOT
alfresco_content_services_0_0_1--[#orange]-|>alfresco_alfresco_pdf_renderer_latest
alfresco_content_services_0_0_1--[#orange]-|>alfresco_alfresco_share_6_0_a
alfresco_content_services_0_0_1--[#orange]-|>alfresco_alfresco_libreoffice_latest
activemq_0_1_0--[#orange]-|>webcenter_activemq_latest
center footer Generated on 2018/04/19 08:58:27 by org.alfresco.deployment.util.PlantUmlChartMapPrinter\nhttps://github.com/Alfresco/alfresco-anaxes-chartmap
@enduml
