@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-identity-service:1.1.0

'There are 3 referenced Helm Charts
artifact "postgresql:0.15.0\n====\n\tpostgresql\n====\n\t0.15.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: databus23\n====\n\tKeywords: postgresql\npostgres\ndatabase\nsql" as postgresql_0_15_0 #LightSteelBlue
artifact "alfresco-identity-service:1.1.0\n====\n\talfresco-identity-service\n====\n\t1.1.0\n====\n\thttps://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: alfresco\nkeycloak\nidentity-service" as alfresco_identity_service_1_1_0 #Chartreuse
artifact "keycloak:4.3.0\n====\n\tkeycloak\n====\n\t4.3.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: unguiculus, thomasdarimont\n====\n\tKeywords: sso\nidm\nopenid connect\nsaml\nkerberos\nldap" as keycloak_4_3_0 #LightBlue

'There are 2 referenced Docker Images
usecase "Image\n====\n\tDocker Hub\n====\n\tpostgres\n====\n\t10.1" as postgres_10_1 #Ivory
usecase "Image\n====\n\tDocker Hub\n====\n\tjboss/keycloak\n====\n\t4.8.3.Final" as jboss_keycloak_4_8_3_Final #LemonChiffon

'Chart Dependencies
alfresco_identity_service_1_1_0--[#green]-|>keycloak_4_3_0
keycloak_4_3_0--[#green]-|>postgresql_0_15_0
postgresql_0_15_0--[#orange]-|>postgres_10_1
keycloak_4_3_0--[#orange]-|>jboss_keycloak_4_8_3_Final

center footer Generated on 2020/02/13 10:22:30 by org.alfresco.deployment.util.PlantUmlChartMapPrinter\nhttps://github.com/Alfresco/alfresco-anaxes-chartmap
@enduml
